# Generated by Django 4.1.7 on 2023-02-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=40, verbose_name='Фамилия')),
                ('phone', models.IntegerField(unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя работника')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель машины')),
                ('is_minibus', models.BooleanField(default=False)),
                ('registration_number', models.CharField(max_length=10, verbose_name='Номер машины')),
                ('vin_number', models.CharField(max_length=100, verbose_name='VIN номер')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_service.clients')),
            ],
        ),
    ]
