# Generated by Django 4.1.7 on 2023-04-17 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Lifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Наименование подьемника')),
                ('is_available_to_client', models.BooleanField(default=False, verbose_name='Доступен для записи клиентом на сайте?')),
                ('is_available_to_minibus', models.BooleanField(default=False, verbose_name='Доступен для ремонта минифургонов?')),
            ],
            options={
                'verbose_name': 'Подъемник',
                'verbose_name_plural': 'Подъемники',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя работника')),
            ],
            options={
                'verbose_name': 'Рабочий',
                'verbose_name_plural': 'Рабочие',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель машины')),
                ('is_minibus', models.BooleanField(default=False)),
                ('registration_number', models.CharField(max_length=10, verbose_name='Номер машины')),
                ('vin_number', models.CharField(blank=True, max_length=100, verbose_name='VIN номер')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_service.clients')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
