# Generated by Django 4.1.7 on 2023-05-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=21, unique=True, verbose_name='Номер телефона'),
        ),
    ]
