# Generated by Django 4.1.7 on 2023-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='last_name',
        ),
        migrations.AddField(
            model_name='clients',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='lifts',
            name='is_available_to_minibus',
            field=models.BooleanField(default=False, verbose_name='Доступен для ремонта минифургонов?'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер телефона'),
        ),
    ]
