# Generated by Django 4.1.7 on 2023-03-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifts',
            name='is_available_to_client',
            field=models.BooleanField(default=False, verbose_name='Доступен для бронирования клиентом на сайте?'),
        ),
        migrations.AlterField(
            model_name='lifts',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Наименование подьемника'),
        ),
    ]
