# Generated by Django 4.1.7 on 2023-02-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'Рабочий', 'verbose_name_plural': 'Рабочие'},
        ),
    ]
