# Generated by Django 4.1.7 on 2023-08-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Статус работы')),
            ],
            options={
                'verbose_name': 'Статус работы',
                'verbose_name_plural': 'Статусы работ',
            },
        ),
        migrations.CreateModel(
            name='TypesOfServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Вид работы')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('is_fixed_price', models.BooleanField(default=True, verbose_name='Фиксированная цена (не зависит от объемов)')),
                ('fixed_repair_time', models.IntegerField(verbose_name='Стандартное время выполнения работы в минутах')),
                ('description', models.TextField(default='', verbose_name='Описание работы')),
                ('is_available_to_client', models.BooleanField(default=False, verbose_name='Доступен для записи клиентом на сайте?')),
                ('is_repair_for_minibus', models.BooleanField(default=False, verbose_name='Тип ремонта относиться к минифургонам?')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.CreateModel(
            name='WorkingConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('size_discount', models.IntegerField(null=True, verbose_name='Размер скидки')),
                ('open_work', models.TimeField(null=True, verbose_name='Время открытия автосервиса')),
                ('close_work', models.TimeField(null=True, verbose_name='Время закрытия автосервиса')),
            ],
            options={
                'verbose_name': 'Условие работы',
                'verbose_name_plural': 'Условия работы',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_begin', models.DateTimeField(verbose_name='Начало работы')),
                ('date_finish_plan', models.DateTimeField(verbose_name='Плановое время окончания')),
                ('date_begin_fact', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Фактическое время начала работ')),
                ('date_finish_fact', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Фактическое время окончания')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Размер скидки')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_service.cars', verbose_name='Модель машины')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_service.clients', verbose_name='Клиент')),
                ('lift_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_service.lifts', verbose_name='Закрепленный подъемник')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_calendar.statusservices', verbose_name='Статус работы')),
                ('type_of_service_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_calendar.typesofservices', verbose_name='Тип работы')),
                ('worker_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='site_service.workers', verbose_name='Закрепленный работник')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
