# Generated by Django 4.1.7 on 2023-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesofservices',
            name='is_fixed_price',
            field=models.BooleanField(default=True, verbose_name='Фиксированная цена (не зависит от объемов)'),
        ),
        migrations.AddField(
            model_name='typesofservices',
            name='is_repair_for_minibus',
            field=models.BooleanField(default=False, verbose_name='Тип ремонта относиться к минифургонам?'),
        ),
    ]
