# Generated by Django 3.2.18 on 2023-05-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date_begin_fact',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Фактическое время начала работ'),
        ),
    ]
