# Generated by Django 4.1.7 on 2023-02-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0002_alter_typesofservices_fixed_repair_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_finish_fact',
            field=models.DateTimeField(blank=True, verbose_name='Фактическое время окончания'),
        ),
        migrations.AlterField(
            model_name='events',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Размер скидки'),
        ),
    ]
