# Generated by Django 4.1.7 on 2023-02-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0003_alter_events_date_finish_fact_alter_events_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_finish_fact',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Фактическое время окончания'),
        ),
    ]
