# Generated by Django 4.1.7 on 2023-03-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0004_alter_events_date_finish_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesofservices',
            name='description',
            field=models.TextField(default='', verbose_name='Описание работы'),
        ),
    ]
