# Generated by Django 4.1.7 on 2023-03-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_service', '0003_alter_cars_vin_number'),
        ('event_calendar', '0005_typesofservices_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='worker_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='site_service.workers', verbose_name='Закрепленный работник'),
        ),
        migrations.AlterField(
            model_name='typesofservices',
            name='is_available_to_client',
            field=models.BooleanField(default=False, verbose_name='Доступен для бронирования клиентом на сайте?'),
        ),
    ]
