# Generated by Django 4.1.7 on 2023-04-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionOfServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('min_price', models.IntegerField(verbose_name='Минимальная цена')),
            ],
            options={
                'verbose_name': 'Предоставляемая услуга',
                'verbose_name_plural': 'Предоставляемые услуги',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя и фамилия')),
                ('type_service', models.CharField(max_length=30, verbose_name='Тип услуги')),
                ('description', models.TextField(verbose_name='Описание отзыва')),
                ('photo', models.ImageField(upload_to='reviews', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя и фамилия')),
                ('description', models.TextField(verbose_name='Описание сотрудника')),
                ('photo', models.ImageField(upload_to='team', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
