# Generated by Django 4.1.7 on 2023-04-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='type_service',
            field=models.CharField(default='example', max_length=30, verbose_name='Тип услуги'),
            preserve_default=False,
        ),
    ]
