# Generated by Django 4.1.7 on 2023-04-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_reviews_type_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='photo',
            field=models.ImageField(upload_to='reviews', verbose_name='фото'),
        ),
    ]
