# Generated by Django 4.1.7 on 2023-04-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_alter_reviews_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='team', verbose_name='фото'),
        ),
    ]
